### ISSUE TITLE
SSL certificate for quid2.org site

### ISSUE THREAD

**Issue by xHasKx** [tittoassini/vscode-planner#3]
Can you please set up an HTTPS SSL certificate for the site http://quid2.org ?
It's easy in our day's thanks to LetsEncrypt.
Without HTTPS lock icon in the browser's address bar, I don't know which user dares to give access to its Google account.

**Comment by tittoassini** [comment]
I will look into that.

**Comment by tittoassini** [comment]
This should be fixed now, let me know if it works for you (you will need to restart vscode).

**Comment by xHasKx** [comment]
Thanks, vscode now opens the https version!
